input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [app_name] {
    mutate {
      add_field => { "[@metadata][target_index]" => "book-service-%{+YYYY.MM.dd}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "unknown-%{+YYYY.MM.dd}" }
    }
  }

  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout {
    codec => rubydebug
  }
}
